### PR TITLE
Update pkg butler files

### PR DESCRIPTION
**Pull request by lrennels**

### CODE REVIEW

**Comment by davidanthoff** [comment]
We should generally never edit these files manually.

**Comment by davidanthoff** [comment]
Ok, actually I'm seeing that this also updates other files, not just the stuff in the `.github` folder. Those other updates are actually ok, but we should just never manually edit the files in the `.github` folder. Instead, make changes to say `Project.toml` and the pkg butler config file, and then the package butler will automatically update the files in the `.github` subfolder.

**Comment by lrennels** [comment]
Makes sense! I wasn’t sure how to trigger it to start running things like package compatibility checks.

**Comment by davidanthoff** [comment]
These github actions disable themselves after a repo has been inactive for too long, that has been happening with a couple of our repos... I don't have a good solution for that yet, other than manually enabling them again...

**Comment by lrennels** [comment]
Ok good to know! That’s actually fine I was mostly trying to do some management if our repos, going through everything on our website and updating, but if it’s just because they’re stale that’s ok.

**Pull request closed without merging**
